language: node_js
node_js: node
script:
- npm run test:lint
- polymer test --skip-plugin local
addons:
  jwt:
    secure: ZQBYlWsBEcVRaELtWWaUi9ouZaRdc+GqyBDHmv+H/IlnGinMJLcUD0tRfFD3n5pVvDVuRXGaHMw7kaF0CM0bd4BJGqV2aWL+erBkMGjEDdIcqxFgqDMzdgGgdDyl+dYhPIAPPUe3L2sPffXcIrAwYmW66iOgkInJiExggqViTaY=
env:
  global:
    SAUCE_USERNAME: Desire2Learn
