language: node_js
node_js:
- "14"
script:
- npm run test
- |
  if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_EVENT_TYPE != "cron" ]; then
    echo "Not a Pull Request and on branch master so bumping version";
    frauci-update-version;
    export TRAVIS_TAG=$(frauci-get-version)
  fi
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=button
  - SAUCE_USERNAME: Desire2Learn
  - secure: TCdj8Ye1Y9eSg2qAb+iIjWG39+w3BWNb5Ada4Pgp6Xyl0hW2n5dYexJQjxWnIR1u7L3Qq7JjIgOaBoNSViuGufhlzAHJZTKst9oeXaThBXY757AvkeM0/0CyGI73b3G/wsZwPQuYYfrmJgxdszus3wvz/Gurri3pUbeEcM9rqgc=
